<?php
/**
 * @file
 * designssquare_com_site_church_data_assets.features.inc
 */

/**
 * Implements hook_content_assets_default_settings().
 */
function designssquare_com_site_church_data_assets_content_assets_default_settings() {
$content_assets = array();

$content_assets = array(
  'public://09_2010_DagsunEdija.jpg' => array(
    'uri' => 'public://09_2010_DagsunEdija.jpg',
    'filename' => '09_2010_DagsunEdija.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/09_2010_DagsunEdija.jpg',
  ),
  'public://09_2010_DagsunEdija_0.jpg' => array(
    'uri' => 'public://09_2010_DagsunEdija_0.jpg',
    'filename' => '09_2010_DagsunEdija_0.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/09_2010_DagsunEdija_0.jpg',
  ),
  'public://avatar.jpg' => array(
    'uri' => 'public://avatar.jpg',
    'filename' => 'avatar.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/avatar.jpg',
  ),
  'public://medium_09_2010_DagsunEdija_0.jpg' => array(
    'uri' => 'public://medium_09_2010_DagsunEdija_0.jpg',
    'filename' => 'medium_09_2010_DagsunEdija_0.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/medium_09_2010_DagsunEdija_0.jpg',
  ),
  'public://styles/thumbnail/public/blog/lelba-brauciens.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/blog/lelba-brauciens.jpg',
    'filename' => 'lelba-brauciens.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/blog/lelba-brauciens.jpg',
  ),
  'public://styles/thumbnail/public/blog/lelba.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/blog/lelba.jpg',
    'filename' => 'lelba.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/blog/lelba.jpg',
  ),
  'public://styles/thumbnail/public/blog/MinneapolisDvesele.png' => array(
    'uri' => 'public://styles/thumbnail/public/blog/MinneapolisDvesele.png',
    'filename' => 'MinneapolisDvesele.png',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/blog/MinneapolisDvesele.png',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/020.jpeg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/020.jpeg',
    'filename' => '020.jpeg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/020.jpeg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/031.jpeg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/031.jpeg',
    'filename' => '031.jpeg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/031.jpeg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/031_0.jpeg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/031_0.jpeg',
    'filename' => '031_0.jpeg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/031_0.jpeg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/2_0.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/2_0.jpg',
    'filename' => '2_0.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/2_0.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/Augstkalnes draudze.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/Augstkalnes draudze.jpg',
    'filename' => 'Augstkalnes draudze.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/Augstkalnes draudze.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/Augstkalnes draudze_0.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/Augstkalnes draudze_0.jpg',
    'filename' => 'Augstkalnes draudze_0.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/Augstkalnes draudze_0.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/birdfat-lg_1.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/birdfat-lg_1.jpg',
    'filename' => 'birdfat-lg_1.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/birdfat-lg_1.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/birdfat-lg_2.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/birdfat-lg_2.jpg',
    'filename' => 'birdfat-lg_2.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/birdfat-lg_2.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/birdfat-lg_3.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/birdfat-lg_3.jpg',
    'filename' => 'birdfat-lg_3.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/birdfat-lg_3.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/birdgreen-lg_1.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/birdgreen-lg_1.jpg',
    'filename' => 'birdgreen-lg_1.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/birdgreen-lg_1.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/birdgreen-lg_2.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/birdgreen-lg_2.jpg',
    'filename' => 'birdgreen-lg_2.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/birdgreen-lg_2.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/birdretro-lg_0.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/birdretro-lg_0.jpg',
    'filename' => 'birdretro-lg_0.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/birdretro-lg_0.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/birdsepia-lg_0.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/birdsepia-lg_0.jpg',
    'filename' => 'birdsepia-lg_0.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/birdsepia-lg_0.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/birdsepia-lg_1.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/birdsepia-lg_1.jpg',
    'filename' => 'birdsepia-lg_1.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/birdsepia-lg_1.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/BushIzbraukums1.jpeg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/BushIzbraukums1.jpeg',
    'filename' => 'BushIzbraukums1.jpeg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/BushIzbraukums1.jpeg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/BushIzbraukums1_0.jpeg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/BushIzbraukums1_0.jpeg',
    'filename' => 'BushIzbraukums1_0.jpeg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/BushIzbraukums1_0.jpeg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/BushLake2.jpeg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/BushLake2.jpeg',
    'filename' => 'BushLake2.jpeg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/BushLake2.jpeg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/BushLake3.jpeg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/BushLake3.jpeg',
    'filename' => 'BushLake3.jpeg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/BushLake3.jpeg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/BushLake4.jpeg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/BushLake4.jpeg',
    'filename' => 'BushLake4.jpeg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/BushLake4.jpeg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/butterfly-lg_0.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/butterfly-lg_0.jpg',
    'filename' => 'butterfly-lg_0.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/butterfly-lg_0.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/butterfly-lg_1.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/butterfly-lg_1.jpg',
    'filename' => 'butterfly-lg_1.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/butterfly-lg_1.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/butterfly-lg_2.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/butterfly-lg_2.jpg',
    'filename' => 'butterfly-lg_2.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/butterfly-lg_2.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/Cake.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/Cake.jpg',
    'filename' => 'Cake.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/Cake.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/flowers-lg_1.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/flowers-lg_1.jpg',
    'filename' => 'flowers-lg_1.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/flowers-lg_1.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/flowers-lg_2.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/flowers-lg_2.jpg',
    'filename' => 'flowers-lg_2.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/flowers-lg_2.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/flowers-lg_3.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/flowers-lg_3.jpg',
    'filename' => 'flowers-lg_3.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/flowers-lg_3.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/grupa.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/grupa.jpg',
    'filename' => 'grupa.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/grupa.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/grupa_0.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/grupa_0.jpg',
    'filename' => 'grupa_0.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/grupa_0.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/IMG_0153.jpeg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/IMG_0153.jpeg',
    'filename' => 'IMG_0153.jpeg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/IMG_0153.jpeg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/leaves-lg.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/leaves-lg.jpg',
    'filename' => 'leaves-lg.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/leaves-lg.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/leaves-lg_0.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/leaves-lg_0.jpg',
    'filename' => 'leaves-lg_0.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/leaves-lg_0.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/leaves-lg_1.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/leaves-lg_1.jpg',
    'filename' => 'leaves-lg_1.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/leaves-lg_1.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/leaves-lg_2.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/leaves-lg_2.jpg',
    'filename' => 'leaves-lg_2.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/leaves-lg_2.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/leaves-lg_3.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/leaves-lg_3.jpg',
    'filename' => 'leaves-lg_3.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/leaves-lg_3.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/leaves-lg_4.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/leaves-lg_4.jpg',
    'filename' => 'leaves-lg_4.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/leaves-lg_4.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/Nicas draudze.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/Nicas draudze.jpg',
    'filename' => 'Nicas draudze.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/Nicas draudze.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/piparkukas_1.jpeg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/piparkukas_1.jpeg',
    'filename' => 'piparkukas_1.jpeg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/piparkukas_1.jpeg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/piparkukas_2.jpeg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/piparkukas_2.jpeg',
    'filename' => 'piparkukas_2.jpeg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/piparkukas_2.jpeg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/piparkukas_3.jpeg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/piparkukas_3.jpeg',
    'filename' => 'piparkukas_3.jpeg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/piparkukas_3.jpeg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/piparkukas_4.jpeg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/piparkukas_4.jpeg',
    'filename' => 'piparkukas_4.jpeg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/piparkukas_4.jpeg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/piparkukas_4_0.jpeg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/piparkukas_4_0.jpeg',
    'filename' => 'piparkukas_4_0.jpeg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/piparkukas_4_0.jpeg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/Sanukste 2013_2.jpeg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/Sanukste 2013_2.jpeg',
    'filename' => 'Sanukste 2013_2.jpeg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/Sanukste 2013_2.jpeg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/slice.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/slice.jpg',
    'filename' => 'slice.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/slice.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/slice_1.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/slice_1.jpg',
    'filename' => 'slice_1.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/slice_1.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/slice_2.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/slice_2.jpg',
    'filename' => 'slice_2.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/slice_2.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/slice_3.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/slice_3.jpg',
    'filename' => 'slice_3.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/slice_3.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/slice_4.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/slice_4.jpg',
    'filename' => 'slice_4.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/slice_4.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/Slokas draudze.jpeg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/Slokas draudze.jpeg',
    'filename' => 'Slokas draudze.jpeg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/Slokas draudze.jpeg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/snail-lg.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/snail-lg.jpg',
    'filename' => 'snail-lg.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/snail-lg.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/snail-lg_0.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/snail-lg_0.jpg',
    'filename' => 'snail-lg_0.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/snail-lg_0.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/snail-lg_1.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/snail-lg_1.jpg',
    'filename' => 'snail-lg_1.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/snail-lg_1.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/snail-lg_2.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/snail-lg_2.jpg',
    'filename' => 'snail-lg_2.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/snail-lg_2.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/snail-lg_3.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/snail-lg_3.jpg',
    'filename' => 'snail-lg_3.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/snail-lg_3.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/Sunakste 2013_1.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/Sunakste 2013_1.jpg',
    'filename' => 'Sunakste 2013_1.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/Sunakste 2013_1.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/Sunakste 2013_1_0.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/Sunakste 2013_1_0.jpg',
    'filename' => 'Sunakste 2013_1_0.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/Sunakste 2013_1_0.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/gallery/Varaklanu draudze.jpeg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/gallery/Varaklanu draudze.jpeg',
    'filename' => 'Varaklanu draudze.jpeg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/gallery/Varaklanu draudze.jpeg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/podcast/baznicas zimejums.png' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/podcast/baznicas zimejums.png',
    'filename' => 'baznicas zimejums.png',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/podcast/baznicas zimejums.png',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/podcast/birdfat-lg_1.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/podcast/birdfat-lg_1.jpg',
    'filename' => 'birdfat-lg_1.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/podcast/birdfat-lg_1.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/podcast/birdgreen-lg.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/podcast/birdgreen-lg.jpg',
    'filename' => 'birdgreen-lg.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/podcast/birdgreen-lg.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/podcast/birdretro-lg.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/podcast/birdretro-lg.jpg',
    'filename' => 'birdretro-lg.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/podcast/birdretro-lg.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/podcast/butterfly-lg_1.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/podcast/butterfly-lg_1.jpg',
    'filename' => 'butterfly-lg_1.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/podcast/butterfly-lg_1.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/podcast/priecigas pedas.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/podcast/priecigas pedas.jpg',
    'filename' => 'priecigas pedas.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/podcast/priecigas pedas.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/podcast/viens uz laipas.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/podcast/viens uz laipas.jpg',
    'filename' => 'viens uz laipas.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/podcast/viens uz laipas.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/portfolio/birdretro-lg_1.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/portfolio/birdretro-lg_1.jpg',
    'filename' => 'birdretro-lg_1.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/portfolio/birdretro-lg_1.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/portfolio/birdsepia-lg_2.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/portfolio/birdsepia-lg_2.jpg',
    'filename' => 'birdsepia-lg_2.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/portfolio/birdsepia-lg_2.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/portfolio/butterfly-lg_5.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/portfolio/butterfly-lg_5.jpg',
    'filename' => 'butterfly-lg_5.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/portfolio/butterfly-lg_5.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/portfolio/flowers-lg_5.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/portfolio/flowers-lg_5.jpg',
    'filename' => 'flowers-lg_5.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/portfolio/flowers-lg_5.jpg',
  ),
  'public://styles/thumbnail/public/designssquare_com/widget/portfolio/leaves-lg_3.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/designssquare_com/widget/portfolio/leaves-lg_3.jpg',
    'filename' => 'leaves-lg_3.jpg',
    'source' => 'sites/all/modules/designssquare_com_site_church/modules/designssquare_com_site_church_data_assets/assets/content/styles/thumbnail/public/designssquare_com/widget/portfolio/leaves-lg_3.jpg',
  ),
);
return $content_assets;
}

/**
 * Implements hook_ctools_plugin_api().
 */
function designssquare_com_site_church_data_assets_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_menu_alias_default_settings().
 */
function designssquare_com_site_church_data_assets_menu_alias_default_settings() {
$menu_alias = array();

$menu_alias = array(
  'main-menu' => array(
    'definition' => array(
      'menu_name' => 'main-menu',
      'title' => 'Main menu',
      'description' => 'The <em>Main</em> menu is used on many sites to show the major sections of the site, often in a top navigation bar.',
    ),
    'links' => array(
      'sākums-latviesu-organizāciju-apvieniba-minesotā' => array(
        'menu_name' => 'main-menu',
        'plid' => 0,
        'link_path' => 'sākums-latviesu-organizāciju-apvieniba-minesotā',
        'link_title' => 'Sākums',
        'options' => array(
          'attributes' => array(),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 0,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'sākums-latviesu-organizāciju-apvieniba-minesotā',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'dāmu-saime' => array(
        'menu_name' => 'main-menu',
        'plid' => 0,
        'link_path' => 'dāmu-saime',
        'link_title' => 'Dāmu saime',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 1,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'dāmu-saime',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'koris' => array(
        'menu_name' => 'main-menu',
        'plid' => 0,
        'link_path' => 'koris',
        'link_title' => 'Koris',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 2,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'koris',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'minesotas-draudzes-skola' => array(
        'menu_name' => 'main-menu',
        'plid' => 0,
        'link_path' => 'minesotas-draudzes-skola',
        'link_title' => 'Skola',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 3,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'minesotas-draudzes-skola',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'bibliotēka-minesotas-draudze' => array(
        'menu_name' => 'main-menu',
        'plid' => 0,
        'link_path' => 'bibliotēka-minesotas-draudze',
        'link_title' => 'Bibliotēka',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 4,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'bibliotēka-minesotas-draudze',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'tautas-dejas-minesota' => array(
        'menu_name' => 'main-menu',
        'plid' => 0,
        'link_path' => 'tautas-dejas-minesota',
        'link_title' => 'Tautas dejas',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 5,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'tautas-dejas-minesota',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'latviešu-organizācijas-apvienība-minesotā' => array(
        'menu_name' => 'main-menu',
        'plid' => 0,
        'link_path' => 'latviešu-organizācijas-apvienība-minesotā',
        'link_title' => 'LOAM',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 6,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'latviešu-organizācijas-apvienība-minesotā',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'mn-draudzes-kalendars/mēnesis' => array(
        'menu_name' => 'main-menu',
        'plid' => 0,
        'link_path' => 'mn-draudzes-kalendars/mēnesis',
        'link_title' => 'Kalendārs',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 7,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'mn-draudzes-kalendars/mēnesis',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
    ),
  ),
  'menu-bottom-menu' => array(
    'definition' => array(
      'menu_name' => 'menu-bottom-menu',
      'title' => 'Bottom Menu',
      'description' => 'menu at the bottom of the page',
    ),
    'links' => array(
      'ds-blog' => array(
        'menu_name' => 'menu-bottom-menu',
        'plid' => 0,
        'link_path' => 'ds-blog',
        'link_title' => 'Avīze',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 0,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'ds-blog',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'sazinies-ar-minesotas-draudzi' => array(
        'menu_name' => 'menu-bottom-menu',
        'plid' => 0,
        'link_path' => 'sazinies-ar-minesotas-draudzi',
        'link_title' => 'Kontakts',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 1,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'sazinies-ar-minesotas-draudzi',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'ds-gallery' => array(
        'menu_name' => 'menu-bottom-menu',
        'plid' => 0,
        'link_path' => 'ds-gallery',
        'link_title' => 'Foto Galerijas',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 3,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'ds-gallery',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'portfolio' => array(
        'menu_name' => 'menu-bottom-menu',
        'plid' => 0,
        'link_path' => 'portfolio',
        'link_title' => 'Portfolio',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 4,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'portfolio',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'ds-newsletter' => array(
        'menu_name' => 'menu-bottom-menu',
        'plid' => 0,
        'link_path' => 'ds-newsletter',
        'link_title' => 'Svētrī†a Zvani',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 4,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'ds-newsletter',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'blog-posts' => array(
        'menu_name' => 'menu-bottom-menu',
        'plid' => 0,
        'link_path' => 'blog-posts',
        'link_title' => 'Blog',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 5,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'blog-posts',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'ds-podcast' => array(
        'menu_name' => 'menu-bottom-menu',
        'plid' => 0,
        'link_path' => 'ds-podcast',
        'link_title' => 'Audio Sprediķis',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 5,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'ds-podcast',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
    ),
  ),
);
return $menu_alias;
}

/**
 * Implements hook_strongarm_override_default_settings().
 */
function designssquare_com_site_church_data_assets_strongarm_override_default_settings() {
$strongarm_override = array();

$strongarm_override[] = array(
  'name' => 'site_403',
  'value' => '',
);
$strongarm_override[] = array(
  'name' => 'site_404',
  'value' => '',
);
$strongarm_override[] = array(
  'name' => 'site_frontpage',
  'value' => 'sākums-latviesu-organizāciju-apvieniba-minesotā',
);
return $strongarm_override;
}
